### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [4tronix/BitCommander#2]
Hi @4tronix  ,

As you might have seen from microsoft/pxt-microbit#3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

Looking at your extension source I believe that your extension falls under this category:

> Use of mbed APIs that are not included in the compatibility layer, or microbit-dal APIs that need different constructors

**Comment by 4tronix** [comment]
This is now fixed in release 1.1.1. But I can't test it "for real" because of the Panic 927 that you've introduced. This Panic is descibed as "You are trying to use a feature designed for micro:bit V2 on a V1 board." which clearly doesn't match what this is.

Please remove the Panic 927 for BitCommander

**Comment by microbit-sam** [comment]
Great, thanks for fixing!

The list is managed by Microsoft, and I'm unable to change it. Please could you create an issue in `pxt-microbit` to request that they remove you from the list?

https://github.com/microsoft/pxt-microbit/issues

**Comment by 4tronix** [comment]
Issue fixed - just waiing on Microsoft to remove from the fail list

**Comment by 4tronix** [comment]
Issue fixed - just waiing on Microsoft to remove from the fail list

**Comment by 4tronix** [comment]
The extension got disabled very quickly. But trying to get it re-enabled seems to take much longer :(
